// <auto-generated />
using System;
using API.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace deliveryFITPackages.API.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("API.Model.Details", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("deliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("houseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("packageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("postedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("recipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("withdrawnAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("zipcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("packageId")
                        .IsUnique();

                    b.ToTable("Details");
                });

            modelBuilder.Entity("API.Model.Package", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("userId")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("API.Model.Details", b =>
                {
                    b.HasOne("API.Model.Package", "Package")
                        .WithOne("Details")
                        .HasForeignKey("API.Model.Details", "packageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("API.Model.Package", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
